In [5]:
import pandas as pd
import seaborn as sns

df = pd.read_csv("../Data/student-mat-missing-data.csv")
df.head()

,Unnamed: 0,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,0,GP,F,18.0,U,GT3,A,4,4,at_home,...,4.0,3.0,4.0,1,1,3.0,6.0,5,6,6
1,1,GP,F,17.0,U,GT3,T,1,1,at_home,...,5.0,3.0,3.0,1,1,3.0,4.0,5,5,6
2,2,GP,F,15.0,U,LE3,T,1,1,at_home,...,4.0,3.0,2.0,2,3,3.0,10.0,7,8,10
3,3,GP,F,15.0,U,GT3,T,4,2,health,...,3.0,2.0,2.0,1,1,5.0,2.0,15,14,15
4,4,GP,F,16.0,U,GT3,T,3,3,other,...,4.0,3.0,2.0,1,2,5.0,4.0,6,10,10

In [6]:
import plotly_express as px
from data_utils import bPlotter as bp 

df.dtypes

Unnamed: 0      int64
school         object
sex            object
age           float64
address        object
famsize        object
Pstatus        object
Medu            int64
Fedu            int64
Mjob           object
Fjob           object
reason         object
guardian       object
traveltime      int64
studytime       int64
failures        int64
schoolsup      object
famsup         object
paid           object
activities     object
nursery        object
higher         object
internet       object
romantic       object
famrel        float64
freetime      float64
goout         float64
Dalc            int64
Walc            int64
health        float64
absences      float64
G1              int64
G2              int64
G3              int64
dtype: object

In [7]:
def baPlot(data, n, i):
    cdata = data.columns[data.isnull().any()]
    fig = px.bar(cdata, x=n, y=i)
    return fig
baPlot(df, "school", "absences")

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [0] but received: school

In [8]:
df[df.isnull().any(1)]

,Unnamed: 0,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
20,20,GP,M,NaN,U,GT3,T,4,3,teacher,...,4.0,4.0,1.0,1,1,1.0,0.0,13,14,15
71,71,GP,M,NaN,U,GT3,T,4,2,other,...,3.0,3.0,3.0,1,1,3.0,0.0,10,10,10
87,87,GP,F,15.0,U,GT3,T,4,2,other,...,5.0,NaN,3.0,1,3,1.0,4.0,13,14,14
99,99,GP,F,16.0,U,GT3,T,4,3,other,...,5.0,NaN,5.0,1,1,3.0,0.0,7,9,8
102,102,GP,M,NaN,U,GT3,T,4,4,services,...,5.0,3.0,3.0,1,1,5.0,4.0,10,13,14
106,106,GP,F,NaN,U,GT3,T,2,2,other,...,5.0,1.0,2.0,1,1,3.0,8.0,7,8,8
121,121,GP,M,NaN,U,GT3,T,2,2,services,...,5.0,5.0,4.0,1,2,5.0,6.0,16,14,15
130,130,GP,F,15.0,R,GT3,T,3,4,services,...,4.0,NaN,2.0,2,2,5.0,0.0,12,0,0
149,149,GP,M,15.0,U,LE3,A,2,1,services,...,4.0,NaN,5.0,2,5,5.0,0.0,8,9,10
151,151,GP,M,16.0,U,LE3,T,2,1,at_home,...,4.0,NaN,4.0,3,5,5.0,6.0,12,13,14
160,160,GP,M,NaN,NaN,LE3,T,2,1,at_home,...,NaN,NaN,NaN,2,2,NaN,NaN,7,6,0
188,188,GP,F,NaN,U,GT3,A,3,3,health,...,3.0,3.0,3.0,1,3,3.0,6.0,8,7,9
191,191,GP,F,NaN,NaN,GT3,T,1,1,at_home,...,NaN,NaN,NaN,1,1,NaN,NaN,8,8,9
214,214,GP,F,NaN,R,LE3,T,4,4,services,...,5.0,2.0,1.0,1,2,3.0,12.0,8,10,10
257,257,GP,M,19.0,U,LE3,A,4,3,services,...,4.0,NaN,1.0,1,1,1.0,12.0,11,11,11
270,270,GP,F,NaN,U,GT3,T,3,3,other,...,4.0,3.0,5.0,3,3,5.0,15.0,9,9,9
276,276,GP,F,NaN,NaN,GT3,A,3,2,other,...,NaN,NaN,NaN,1,1,NaN,NaN,10,9,9
293,293,GP,F,NaN,NaN,LE3,T,3,1,services,...,NaN,NaN,NaN,1,1,NaN,NaN,18,18,18
308,308,GP,M,19.0,R,GT3,T,3,3,other,...,4.0,NaN,3.0,1,2,5.0,0.0,15,12,12
330,330,GP,M,18.0,U,LE3,T,2,2,other,...,4.0,NaN,5.0,2,4,5.0,2.0,9,8,8
343,343,GP,F,17.0,U,GT3,A,2,2,at_home,...,3.0,NaN,1.0,1,2,4.0,0.0,9,8,0
348,348,GP,F,NaN,U,GT3,T,4,3,health,...,4.0,4.0,3.0,1,3,4.0,0.0,13,15,15
359,359,MS,F,18.0,U,LE3,T,1,1,at_home,...,5.0,NaN,2.0,1,1,4.0,0.0,18,16,16
372,372,MS,F,17.0,U,GT3,T,2,2,other,...,3.0,NaN,3.0,1,1,3.0,8.0,13,11,11
385,385,MS,F,NaN,NaN,GT3,T,2,2,at_home,...,NaN,NaN,NaN,1,3,NaN,NaN,10,9,10

In [17]:
import seaborn as sns
df = df.apply(pd.to_numeric, errors="ignore")
df2
sns.displot(data=df.isnull().melt(value_name="missing"), y="variable", hue="missing", multiple="fill")

ValueError: Could not interpret value `variable` for parameter `y`

In [14]:
df2 = mis[df["age", "famrel", "freetime", "goout", "health", "absences"]]

KeyError: ('age', 'famrel', 'freetime', 'goout', 'health', 'absences')